swagger: '2.0'
info:
  title: <%= title %>
  description: <%= description %>
  version: <%= version %>
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
# the domain of the service
host: <%= host %>
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: <%= basePath %>
consumes:
  - application/json
produces:
  - application/json
security:
  - type: basic
    in: header
  - type: oauth2
    authorizationUrl: /api/oauth
    flow: [implicit, password, application, accessCode]
externalDocs:
  url: http://agile-iot.github.io/agile-api-spec/build/html/api.html
  description: DBus AGILE API spec
paths:
<%= paths %>
definitions:
<%= types %>
